# Numpy Detour

## Delete Elements

In [19]:
import numpy as np

arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
mask = np.ones(len(arr), dtype=bool)
mask[0:2] = False

# hide 1st and 2nd rows
result = arr[mask, ...]
print(result)

# hide 1st and 2nd cols
result = arr[..., mask]
print(result)

[[6 7 8]]
[[2]
 [5]
 [8]]


In [23]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# delete the 2nd element/row along 1st dimension
result = np.delete(arr, 1, 0)
print(result)

# delete the 2nd element/col along the 2nd dimension
result = np.delete(arr, 1, 1)
print(result)

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  3  4]
 [ 5  7  8]
 [ 9 11 12]]


## Size of Array

In [29]:
arr = np.array([[1,2],[3,4],[5,6]])
np.size(arr, 0)

3

## Reshape

In [34]:
a = np.zeros((10, 2))
a.reshape(20)
a.reshape(20, 1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

## Arithmetics

In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
diffs = arr - np.array([1, 1, 1])
diffs_square = diffs ** 2
sqrts = np.sqrt(diffs_square)

[[0 1 2]
 [3 4 5]]
[[ 0  1  4]
 [ 9 16 25]]


array([[0., 1., 2.],
       [3., 4., 5.]])

In [45]:
arr = np.array([1, 2, 3, 4])

np.dot(arr, arr)
# vs.
arr * arr

array([ 1,  4,  9, 16])

In [47]:
np.abs(np.array([-1, -12]))

array([ 1, 12])